### PR TITLE
Fix for hibernate 5

### PR DESCRIPTION
**Pull request by rtisma**
Addresses issue #11

### CODE REVIEW

File: src/main/java/com/marvinformatics/hibernate/json/JsonUserType.java [hunk 1]
```diff
@@ -68,7 +68,6 @@ public boolean isMutable() {
         return true;
     }
 
-    @Override
     public void nullSafeSet(PreparedStatement st, Object value, int index, SessionImplementor session) throws HibernateException, SQLException {
```
Comment (velo) [inline src/main/java/com/marvinformatics/hibernate/json/JsonUserType.java]: if this method is no longer part of the implementation, I think it's safe to take it out.

File: src/main/java/com/marvinformatics/hibernate/json/JsonUserType.java [hunk 2]
```diff
@@ -79,7 +78,14 @@ public void nullSafeSet(PreparedStatement st, Object value, int index, SessionIm
         st.setObject(index, dataObject);
     }
 
-    @Override
+    public Object nullSafeGet(ResultSet rs, String[] names, SharedSessionContractImplementor session, Object owner) throws HibernateException, SQLException {
+        return nullSafeGet(rs, names, (SessionImplementor) session, owner);
```
Comment (velo) [inline src/main/java/com/marvinformatics/hibernate/json/JsonUserType.java]: I don't think this cast is either safe nor necessary.

**Review by velo — CHANGES_REQUESTED** [review]
What about we delete the old method?!

File: src/main/java/com/marvinformatics/hibernate/json/JsonUserType.java (hunk 2 above)
Comment (rtisma) [reply src/main/java/com/marvinformatics/hibernate/json/JsonUserType.java]: right. I blindly copied the fix from my other project, which has jsonb working with hibernate using sprint boot 2.0.1. ill update this.

**Comment by rtisma** [comment]
not too sure why its failing with 
```
queryJson(com.marvinformatics.hibernate.json.JsonExpressionsTest)  Time elapsed: 1.73 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.hibernate.Session.createQuery(Ljava/lang/String;)Lorg/hibernate/Query;
	at com.querydsl.jpa.hibernate.DefaultSessionHolder.createQuery(DefaultSessionHolder.java:36)
	at com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:104)
	at com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:97)
	at com.querydsl.jpa.hibernate.AbstractHibernateQuery.fetch(AbstractHibernateQuery.java:174)
	at com.marvinformatics.hibernate.json.JsonExpressionsTest.queryJson(JsonExpressionsTest.java:104)
```
when hibernate-core 5.2.16-Final has the method
https://github.com/hibernate/hibernate-orm/blob/5.2.16/hibernate-core/src/main/java/org/hibernate/Session.java#L1142

only hibernate-core 5.2.16-Final is loaded on the classpath
